defaults: &defaults
  working_directory: ~/scotty-story-board
  docker:
    - image: fpco/stack-build:lts-9.0
      environment:
        DATABASE_URL: postgres://user@localhost:5432/scotty-story-board
    - image: postgres:9.6.2
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: ""
        POSTGRES_DB: scotty-story-board

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-stack-cache-{{ checksum "stack.yaml" }}-{{ checksum "scotty-story-board.cabal" }}
      - run: stack setup
      - run: stack build --only-dependencies
      - run: stack build --test --no-run-tests
      - save_cache:
          key: v1-stack-cache-{{ checksum "stack.yaml" }}-{{ checksum "scotty-story-board.cabal" }}
          paths:
            - ~/.stack
            - .stack-work
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-stack-cache-{{ checksum "stack.yaml" }}-{{ checksum "scotty-story-board.cabal" }}
      - run: stack exec migrate test
      - run: stack test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
